export const products = [
  {
    SKU: "AB12CD",
    name: "DVD Movie",
    price: 10,
    type: "DVD",
    size: "300MB",
  },
  {
    SKU: "EF34GH",
    name: "Furniture Piece",
    price: 200,
    type: "Furniture",
    height: 45,
    width: 60,
    length: 90,
  },
  {
    SKU: "IJ56KL",
    name: "Book Title",
    price: 15,
    type: "Book",
    weight: "0.11kg",
  },
  {
    SKU: "MN78OP",
    name: "DVD Series",
    price: 50,
    type: "DVD",
    size: "2GB",
  },
  {
    SKU: "QR90ST",
    name: "Furniture Piece",
    price: 180,
    type: "Furniture",
    height: 75,
    width: 80,
    length: 120,
  },
  {
    SKU: "UV12WX",
    name: "Book Title",
    price: 25,
    type: "Book",
    weight: "0.15kg",
  },
  {
    SKU: "YZ34AB",
    name: "DVD Movie",
    price: 12,
    type: "DVD",
    size: "700MB",
  },
  {
    SKU: "CD56EF",
    name: "Furniture Piece",
    price: 250,
    type: "Furniture",
    height: 60,
    width: 70,
    length: 100,
  },
  {
    SKU: "GH78IJ",
    name: "Book Title",
    price: 18,
    type: "Book",
    weight: "0.13kg",
  },
  {
    SKU: "KL90MN",
    name: "DVD Series",
    price: 55,
    type: "DVD",
    size: "1.5GB",
  },
  {
    SKU: "OP12QR",
    name: "Furniture Piece",
    price: 220,
    type: "Furniture",
    height: 80,
    width: 65,
    length: 110,
  },
  {
    SKU: "ST34UV",
    name: "Book Title",
    price: 30,
    type: "Book",
    weight: "0.2kg",
  },
  {
    SKU: "WX56YZ",
    name: "DVD Movie",
    price: 15,
    type: "DVD",
    size: "500MB",
  },
  {
    SKU: "AB78CD",
    name: "Furniture Piece",
    price: 280,
    type: "Furniture",
    height: 70,
    width: 75,
    length: 130,
  },
  {
    SKU: "EF90GH",
    name: "Book Title",
    price: 22,
    type: "Book",
    weight: "0.18kg",
  },
];
